trigger:
- master

jobs:
- job: Nugetbuild
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 240
  steps:
  - checkout: self
    submodules: recursive
  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.StagingDirectory)\_'
  - task: UseDotNet@2
    displayName: 'Use dotnet sdk 3.x'
    inputs:
      version: 3.x
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific' # Options: current, specific
      project: 'mrtk_ros' # Required when source == Specific
      pipeline: 110 # Required when source == Specific
      buildVersionToDownload: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
      artifactName: 'ros2vcpkg'
  - script: |
      dir /s %System_ArtifactsDirectory%
      mkdir c:\opt\vcpkg
      7z x %System_ArtifactsDirectory%\ros2vcpkg\vcpkg.zip.001 -oc:\opt
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call init.cmd
      call build.cmd
      cd src
      build.cmd
      cd ..\nuget
      call build_nuget.cmd
    displayName: Build ROS2 Nuget Package
    workingDirectory: '$(Build.StagingDirectory)\_'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: .\target\log
      artifactName: ros2dotnet-log'
    condition: always()
