trigger:
- master

jobs:
- job: Nugetbuild
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 240
  steps:
  - checkout: self
    submodules: recursive
  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.StagingDirectory)\_'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call init.cmd
      call build.cmd
      cd nuget
      call build_nuget.cmd
    displayName: Initialize isolated build
    workingDirectory: '$(Build.StagingDirectory)\_'
